<a href="https://colab.research.google.com/github/KalharaBatangala/Numpy-for-AI/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import math

In [36]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [37]:
myl = np.array([[2,2,3,4,5],
                [2,2,3,4,5]])

myl.ndim #Return number of dimensions
myl.shape # Return number of elements in each dimension   (2,5)
len(myl.shape) == myl.ndim  # Is it the same as no. of dimensions?
myl.size   # Total number of elements  (10)
math.prod(myl.shape) == myl.size    # no. of elements is each dimension * no. of dimensions

myl.dtype

dtype('int64')

**Create a basic array**

In [38]:
array = np.zeros([2,3])
array
array.shape
math.prod(array.shape) == array.size

True

In [39]:
array_ones = np.ones([3,2], dtype=int)
array_ones
array_ones[1][1] = 5
np.sum(array_ones)


10

In [40]:
# Empty array
array_emt = np.empty([3,2])  #Because of speed
array_emt



array([[4.83214543e-310, 0.00000000e+000],
       [2.05833592e-312, 2.18565567e-312],
       [5.63998211e-018, 4.28096524e-307]])

In [41]:
# Range of elements
np.arange(2,9,2)

array([2, 4, 6, 8])

**Adding, removing, and sorting elements**

In [42]:
myarr = np.array([1,2,9,4,3,7,1,5,8,2])
myarr
np.sort(myarr)

array([1, 1, 2, 2, 3, 4, 5, 7, 8, 9])

Concatinate arrays

In [43]:
arr1 = np.array([5,6,7])
arr2 = np.array([11,24,89])
arrfinal = np.concatenate((arr1,arr2))
arrfinal

array([ 5,  6,  7, 11, 24, 89])

In [44]:
one = np.array([[1,2,3],[4,5,6],[11,2,45]])
two = np.array([[7,6,90]])

final = np.concatenate((one,two), axis=0)
final

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11,  2, 45],
       [ 7,  6, 90]])

In [45]:
final2 = np.concatenate((one, two.T), axis=1)
final2.shape

arr3 = np.array([[[[1,2],
                  [3,4],
                  [7,5]],

                 [[2,3],
                 [12,13],
                 [54,44]]],

                 [[[1,2],
                  [3,4],
                  [7,5]],

                 [[2,3],
                 [12,13],
                 [54,44]]]])
arr3.shape

(2, 2, 3, 2)

In [46]:
new_arr = np.arange(12)
new_arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**1D array -> 2D array   (Add new axis to array)**

In [47]:
S_arr = np.arange(7)
print(S_arr.shape)
#S_arr = S_arr[np.newaxis, :]  # Convert to a row vector
S_arr.shape

S_col = S_arr[:, np.newaxis]
S_col.shape

(7,)


(7, 1)

In [48]:
data = np.arange(12)
data.reshape(3,4)
data[data<7]    ## print all values less than 7
data[data>7]    ## print all values greater than 7
data[(data%2==0) & (data>3)]    ## Satisfy both the conditions divisible by 2 & (>3)

array([ 4,  6,  8, 10])

**create an array from existing data**

In [49]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

b = a[3:8]   ## From Index position 3 through (not included 8) index positon 8
b

array([4, 5, 6, 7, 8])

In [50]:
## Stack two arrays

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a3 = np.hstack((a1, a2))
a3

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
myarray = np.arange(1,19).reshape(3,6)
print(myarray)
np.vsplit(myarray, 3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]])]

**Views (a shallow copy)**

* important NumPy concept
*saves memory and is faster
*modifying data in a view also modifies the original array!


In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1[0] = 99

a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Basic array operations**

In [53]:
ones = np.ones([3,4], dtype=int)
twos = np.ones([3,4], dtype=int)*2
twos.sum(axis=1)    ## Summing along horizontal axis
twos.sum(axis=0)    ## Summming along vertical axis

array([6, 6, 6, 6])

In [54]:
nw_a = np.array([1,2,3,4,5,6])
nw_a.max()
nw_a.mean()

3.5

In [55]:
Tq = np.arange(12)

Tq = Tq.reshape(3,4)
sum = Tq.sum(axis=1)
print(Tq)
sum

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [56]:
hnz = np.array([1,2,3,3,9,8,66,7,3,23,8,1,90,3,7,66,23,11,2,3,66])
np.unique(hnz)        ## Print uniqu values in an array
unival, ind = np.unique(hnz, return_index=True)
print(unival)
print(ind)

[ 1  2  3  7  8  9 11 23 66 90]
[ 0  1  2  7  5  4 17  9  6 12]


**Transposing and reshaping a matrix**

In [57]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
## Reshape
reshp = mat.reshape( 1,9)
print(reshp)
mat.T     ## Transpose of the matrix


## Flip the matrix
flipped = np.flip(reshp)
flipped

[[1 2 3 4 5 6 7 8 9]]


array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [58]:
arr2d = np.arange(12).reshape(3,4)
print(arr2d)
reverse2d = np.flip(arr2d, axis=0)
reverse2d

## You can flip only one row also
# reversed2d_one = arr2d
# reversed2d_one[1] = np.flip(arr2d[1])
# reversed2d_one

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

**Flattening multidimensional arrays**

In [59]:
U = np.arange(1,13).reshape(3,4)
print(U.flatten())
U       ## If you used ravel function, changes reflects to parent array also

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Working with mathematical formulas**

In [60]:
## Mean Square Error
pred = np.arange(1,13).reshape(3,4)
print("pred:",pred)
y = np.flip(pred).reshape(3,4)
print("y:",y)
array_size = np.size(pred)

MSE = (1/array_size) * np.sum(np.square(pred-y))
MSE

pred: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
y: [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


47.666666666666664