<a href="https://colab.research.google.com/github/KalharaBatangala/Numpy-for-AI/blob/main/numpy_calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [18]:
arr1 = np.array([[1,2,3],
                 [3,2,1]])
arr2 = np.array([[6,5],
                 [2,4],
                 [1,5]])

#mul = arr1*arr2
#print(mul)
#prod = np.multiply(arr1,arr2)
#print(prod)
dot = np.dot(arr1,arr2)
print(dot)

[[13 28]
 [23 28]]


In [32]:
a = np.arange(9).reshape(3,3)
b = np.arange(9)
b = np.flip(b).reshape(3,3)

diff = a - b
print(diff)
c = np.linalg.norm(diff, ord=2, keepdims=True) # normalization
c

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


array([[14.69693846]])