<a href="https://colab.research.google.com/github/KalharaBatangala/Numpy-for-AI/blob/main/numpy_calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [2]:
arr1 = np.array([[1,2,3],
                 [3,2,1]])
arr2 = np.array([[6,5],
                 [2,4],
                 [1,5]])

#mul = arr1*arr2
#print(mul)
#prod = np.multiply(arr1,arr2)
#print(prod)
dot = np.dot(arr1,arr2)
print(dot)

# math.exp() only for real numbers. but in DL, we have to deal with matrices,
# therefore, np.exp() is used over math.exp()

[[13 28]
 [23 28]]


In [3]:
a = np.arange(9).reshape(3,3)
b = np.arange(9)
b = np.flip(b).reshape(3,3)

diff = a - b
print(diff)
c = np.linalg.norm(diff, ord=2, keepdims=True) # normalization
c

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


array([[14.69693846]])

In [4]:
# Keepdims = True ( for broadcasting)
# Normalization
# x/||x||
# Before doing DL tasks, images are read as 1D vector.
# They are in 3D arrays as matrices, --> converted to 1D vector

In [7]:
# Sigmoid function

arr_data = np.arange(50).reshape(-1,1)      # np.reshape(-1,1) --> convert automatically to number of rows
arr_data

# sigmoid
s = 1/(1+np.exp(arr_data))
s

array([[5.00000000e-01],
       [2.68941421e-01],
       [1.19202922e-01],
       [4.74258732e-02],
       [1.79862100e-02],
       [6.69285092e-03],
       [2.47262316e-03],
       [9.11051194e-04],
       [3.35350130e-04],
       [1.23394576e-04],
       [4.53978687e-05],
       [1.67014218e-05],
       [6.14417460e-06],
       [2.26032430e-06],
       [8.31528028e-07],
       [3.05902227e-07],
       [1.12535162e-07],
       [4.13993755e-08],
       [1.52299795e-08],
       [5.60279641e-09],
       [2.06115362e-09],
       [7.58256042e-10],
       [2.78946809e-10],
       [1.02618796e-10],
       [3.77513454e-11],
       [1.38879439e-11],
       [5.10908903e-12],
       [1.87952882e-12],
       [6.91440011e-13],
       [2.54366565e-13],
       [9.35762297e-14],
       [3.44247711e-14],
       [1.26641655e-14],
       [4.65888615e-15],
       [1.71390843e-15],
       [6.30511676e-16],
       [2.31952283e-16],
       [8.53304763e-17],
       [3.13913279e-17],
       [1.15482242e-17],
