<a href="https://colab.research.google.com/github/KalharaBatangala/Numpy-for-AI/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import math

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
myl = np.array([[2,2,3,4,5],
                [2,2,3,4,5]])

myl.ndim #Return number of dimensions
myl.shape # Return number of elements in each dimension   (2,5)
len(myl.shape) == myl.ndim  # Is it the same as no. of dimensions?
myl.size   # Total number of elements  (10)
math.prod(myl.shape) == myl.size    # no. of elements is each dimension * no. of dimensions

myl.dtype

dtype('int64')

**Create a basic array**

In [14]:
array = np.zeros([2,3])
array
array.shape
math.prod(array.shape) == array.size

True

In [23]:
array_ones = np.ones([3,2], dtype=int)
array_ones
array_ones[1][1] = 5
np.sum(array_ones)


10

In [26]:
# Empty array
array_emt = np.empty([3,2])  #Because of speed
array_emt



array([[4.9e-324, 4.9e-324],
       [4.9e-324, 2.5e-323],
       [4.9e-324, 4.9e-324]])

In [30]:
# Range of elements
np.arange(2,9,2)

array([2, 4, 6, 8])

**Adding, removing, and sorting elements**

In [33]:
myarr = np.array([1,2,9,4,3,7,1,5,8,2])
myarr
np.sort(myarr)

array([1, 1, 2, 2, 3, 4, 5, 7, 8, 9])

Concatinate arrays

In [35]:
arr1 = np.array([5,6,7])
arr2 = np.array([11,24,89])
arrfinal = np.concatenate((arr1,arr2))
arrfinal

array([ 5,  6,  7, 11, 24, 89])