<a href="https://colab.research.google.com/github/KalharaBatangala/Numpy-for-AI/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import math

In [44]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [45]:
myl = np.array([[2,2,3,4,5],
                [2,2,3,4,5]])

myl.ndim #Return number of dimensions
myl.shape # Return number of elements in each dimension   (2,5)
len(myl.shape) == myl.ndim  # Is it the same as no. of dimensions?
myl.size   # Total number of elements  (10)
math.prod(myl.shape) == myl.size    # no. of elements is each dimension * no. of dimensions

myl.dtype

dtype('int64')

**Create a basic array**

In [46]:
array = np.zeros([2,3])
array
array.shape
math.prod(array.shape) == array.size

True

In [47]:
array_ones = np.ones([3,2], dtype=int)
array_ones
array_ones[1][1] = 5
np.sum(array_ones)


10

In [48]:
# Empty array
array_emt = np.empty([3,2])  #Because of speed
array_emt



array([[4.84317848e-310, 0.00000000e+000],
       [9.76118064e-313, 1.78247646e-312],
       [9.54898106e-313, 2.76676762e-322]])

In [49]:
# Range of elements
np.arange(2,9,2)

array([2, 4, 6, 8])

**Adding, removing, and sorting elements**

In [50]:
myarr = np.array([1,2,9,4,3,7,1,5,8,2])
myarr
np.sort(myarr)

array([1, 1, 2, 2, 3, 4, 5, 7, 8, 9])

Concatinate arrays

In [51]:
arr1 = np.array([5,6,7])
arr2 = np.array([11,24,89])
arrfinal = np.concatenate((arr1,arr2))
arrfinal

array([ 5,  6,  7, 11, 24, 89])

In [66]:
one = np.array([[1,2,3],[4,5,6],[11,2,45]])
two = np.array([[7,6,90]])

final = np.concatenate((one,two), axis=0)
final

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11,  2, 45],
       [ 7,  6, 90]])

In [78]:
final2 = np.concatenate((one, two.T), axis=1)
final2.shape

arr3 = np.array([[[[1,2],
                  [3,4],
                  [7,5]],

                 [[2,3],
                 [12,13],
                 [54,44]]],

                 [[[1,2],
                  [3,4],
                  [7,5]],

                 [[2,3],
                 [12,13],
                 [54,44]]]])
arr3.shape

(2, 2, 3, 2)

In [93]:
new_arr = np.arange(12)
new_arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**1D array -> 2D array   (Add new axis to array)**

In [101]:
S_arr = np.arange(7)
print(S_arr.shape)
#S_arr = S_arr[np.newaxis, :]  # Convert to a row vector
S_arr.shape

S_col = S_arr[:, np.newaxis]
S_col.shape

(7,)


(7, 1)

In [129]:
data = np.arange(12)
data.reshape(3,4)
data[data<7]    ## print all values less than 7
data[data>7]    ## print all values greater than 7
data[(data%2==0) & (data>3)]    ## Satisfy both the conditions divisible by 2 & (>3)

array([ 4,  6,  8, 10])

**create an array from existing data**

In [131]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

b = a[3:8]   ## From Index position 3 through (not included 8) index positon 8
b

array([4, 5, 6, 7, 8])

In [133]:
## Stack two arrays

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a3 = np.hstack((a1, a2))
a3

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [144]:
myarray = np.arange(1,19).reshape(3,6)
print(myarray)
np.vsplit(myarray, 3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]])]

**Views (a shallow copy)**

* important NumPy concept
*saves memory and is faster
*modifying data in a view also modifies the original array!


In [150]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1[0] = 99

a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Basic array operations**

In [171]:
ones = np.ones([3,4], dtype=int)
twos = np.ones([3,4], dtype=int)*2
twos.sum()


24